server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  #连接远程仓库
  cloud:
      config:
        server:
          git:
            uri:  https://gitee.com/gmlic/springcloud-config.git  #https地址
#http://127.0.0.1:3344/application-dev.yml
# 通过 config-server可以连接到git, 访问其中的资源以及配置